apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-runner-manager-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: code-runner-manager-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]

  #? Allows executing commands inside pods
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-runner-manager-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: code-runner-manager-sa
    namespace: default
roleRef:
  kind: Role
  name: code-runner-manager-role
  apiGroup: rbac.authorization.k8s.io
